services:
  # using ovishpc/ldms-agg for both, since it has both sampling and 
  # aggregation tools.
  # src: https://github.com/ovis-hpc/ldms-containers
  samp:
    image: ovishpc/ldms-agg
    network_mode: host
    pid: host
    privileged: true
    environment:
      - COMPID=1
    volumes:
      - /etc/munge/munge.key:/etc/munge/munge.key:ro
      - ./conf:/conf:ro
    command: -x sock:10001 -l /samp.log -c /conf/samp.conf
  agg:
    image: ovishpc/ldms-agg
    network_mode: host
    pid: host
    privileged: true
    depends_on:
      - samp
    environment:
      - COMPID=2
    volumes:
      - ./storage:/storage:rw
      - /etc/munge/munge.key:/etc/munge/munge.key:ro
      - ./conf:/conf:ro
    command: -x sock:20001 -l /agg.log -c /conf/agg.conf
