services:
  samp:
    image: ovishpc/ldms-agg
    network_mode: host
    pid: host
    privileged: true
    environment:
      - COMPID=1
    volumes:
      - /etc/munge/munge.key:/etc/munge/munge.key:ro
      - ./conf:/conf:ro
      # - ./logs:/var/log # uncomment this for debugging
    command: -x sock:10001 -l /var/log/samp.log -c /conf/samp.conf
  agg:
    image: ovishpc/ldms-agg
    network_mode: host
    pid: host
    privileged: true
    # TODO: repeat these env vars for samp as well
    environment:
      - LDMSD_FLAGS=TODO:
    depends_on:
      - samp
    environment:
      - COMPID=2
    volumes:
      - ./storage:/storage:rw
      - /etc/munge/munge.key:/etc/munge/munge.key:ro
      - ./conf:/conf:ro
      # - ./logs:/var/log # uncomment this for debugging
    command: -x sock:20001 -l /var/log/agg.log -c /conf/agg.conf
